import type { MigrationInterface, QueryRunner } from 'typeorm';

type BaselineQuery = Readonly<{ query: string; parameters: readonly unknown[] }>;

export const COMMUNITY_BASELINE_SCHEMA_DIGEST = "sha256:6ae33ce697932a72cc9df48b6e853cce0b4187896839c1fa4ae7f66d76aafae9";

const UP_QUERIES: readonly BaselineQuery[] = Object.freeze([
  {"query":"CREATE TABLE \"agents\" (\"id\" uuid NOT NULL, \"workspaceId\" character varying NOT NULL, \"name\" character varying NOT NULL, \"apiName\" character varying(100) NOT NULL, \"label\" character varying, \"description\" text, \"icon\" character varying, \"avatarPresetKey\" character varying, \"prompt\" text, \"modelId\" character varying, \"responseFormat\" character varying, \"roleId\" uuid, \"serviceUserId\" uuid, \"isActive\" boolean NOT NULL DEFAULT true, \"isCustom\" boolean NOT NULL DEFAULT false, \"modelConfiguration\" jsonb, \"evaluationInputs\" jsonb, \"applicationId\" character varying, \"type\" character varying(20) NOT NULL DEFAULT 'custom', \"capabilities\" text array, \"triggerConfig\" jsonb, \"guardrailRules\" jsonb, \"knowledgeBaseIds\" uuid array, \"sopDocumentIds\" uuid array, \"modelConfig\" jsonb, \"orgNodeId\" uuid, \"deployedAt\" TIMESTAMP WITH TIME ZONE, \"version\" integer NOT NULL DEFAULT '1', \"status\" character varying(20) NOT NULL DEFAULT 'draft', \"definition\" jsonb, \"createdAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_9c653f28ae19c5884d5baf6a1d9\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE INDEX \"IDX_891465b3cee1cfe275594eb1cd\" ON \"agents\" (\"workspaceId\") ","parameters":[]},
  {"query":"CREATE TYPE \"public\".\"react_steps_resolution_mode_enum\" AS ENUM('active_snapshot', 'candidate_test')","parameters":[]},
  {"query":"CREATE TABLE \"react_steps\" (\"id\" uuid NOT NULL, \"executionId\" uuid NOT NULL, \"workspace_id\" uuid, \"source_workspace_id\" uuid, \"resolution_mode\" \"public\".\"react_steps_resolution_mode_enum\", \"candidate_isolation_binding_id\" uuid, \"candidate_isolation_snapshot_hash\" character varying(71), \"release_set_id\" uuid, \"flow_version_id\" uuid, \"flow_node_id\" character varying(160), \"stepIndex\" integer NOT NULL, \"traceId\" character varying(100), \"correlationId\" character varying(100), \"actorType\" character varying(50), \"actorId\" character varying(100), \"source\" character varying(100), \"thoughtReasoning\" text, \"thoughtPlan\" text, \"thoughtConfidence\" numeric(3,2), \"actionType\" character varying(20) NOT NULL, \"toolName\" character varying(100), \"toolInput\" jsonb, \"generatePrompt\" text, \"observationSuccess\" boolean, \"observationOutput\" jsonb, \"observationError\" text, \"guardrailTriggered\" boolean NOT NULL DEFAULT false, \"inputTokens\" integer NOT NULL DEFAULT '0', \"outputTokens\" integer NOT NULL DEFAULT '0', \"model\" character varying(50), \"aiProviderStamp\" jsonb, \"durationMs\" integer, \"createdAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_37ad89a5057e7b8643849b1dcca\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE UNIQUE INDEX \"UQ_react_steps_workspace_execution_id\" ON \"react_steps\" (\"workspace_id\", \"executionId\", \"id\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_7550a7c4d20f106ffddfc74a92\" ON \"react_steps\" (\"source_workspace_id\", \"release_set_id\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_abb1456d082dc4c885bec68f21\" ON \"react_steps\" (\"source_workspace_id\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_e93108251ad8ecd567a435f096\" ON \"react_steps\" (\"executionId\", \"correlationId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_de8fbe47b4d7da2bf10a0d5a5e\" ON \"react_steps\" (\"executionId\", \"traceId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_91ea1fd419e85e7975349da670\" ON \"react_steps\" (\"executionId\", \"stepIndex\") ","parameters":[]},
  {"query":"CREATE TYPE \"public\".\"tool_call_records_resolution_mode_enum\" AS ENUM('active_snapshot', 'candidate_test')","parameters":[]},
  {"query":"CREATE TYPE \"public\".\"tool_call_records_status_enum\" AS ENUM('STARTED', 'DENIED', 'BLOCKED', 'REQUIRES_APPROVAL', 'RUNNING', 'SUCCEEDED', 'FAILED', 'COMPLETION_UNKNOWN')","parameters":[]},
  {"query":"CREATE TABLE \"tool_call_records\" (\"id\" uuid NOT NULL, \"executionId\" uuid, \"workspace_id\" uuid, \"source_workspace_id\" uuid, \"resolution_mode\" \"public\".\"tool_call_records_resolution_mode_enum\", \"candidate_isolation_binding_id\" uuid, \"candidate_isolation_snapshot_hash\" character varying(71), \"agent_execution_id\" uuid, \"flow_execution_id\" uuid, \"flow_step_log_id\" uuid, \"flow_version_id\" uuid, \"flow_node_id\" character varying(160), \"release_set_id\" uuid, \"function_revision_id\" uuid, \"function_execution_id\" uuid, \"descriptor_hash\" character varying(71), \"published_checksum\" character varying(71), \"runtime_provider_id\" character varying(96), \"idempotency_key_hash\" character varying(96), \"static_binding_revision_id\" uuid, \"static_binding_checksum\" character varying(71), \"static_binding_generation\" bigint, \"static_connector_subcall_ordinal\" integer, \"static_connector_request_digest\" character varying(71), \"stepId\" uuid, \"toolName\" character varying(200) NOT NULL, \"traceId\" character varying(100), \"correlationId\" character varying(100), \"actorType\" character varying(50), \"actorId\" character varying(100), \"source\" character varying(100), \"toolCategory\" character varying(20), \"input\" jsonb, \"output\" jsonb, \"status\" \"public\".\"tool_call_records_status_enum\", \"lease_expires_at\" TIMESTAMP WITH TIME ZONE, \"last_heartbeat_at\" TIMESTAMP WITH TIME ZONE, \"input_digest\" character varying(71), \"output_digest\" character varying(71), \"redaction_applied\" boolean, \"attempt\" integer, \"error_code\" character varying(100), \"permissionCheck\" character varying(10), \"permissionDetail\" text, \"guardrailCheck\" character varying(20), \"guardrailRuleId\" uuid, \"durationMs\" integer, \"createdAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_314c2c553849f575034d9a1c63a\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE INDEX \"IDX_dc3c86e33a0b29c896721a27a7\" ON \"tool_call_records\" (\"workspace_id\", \"flow_execution_id\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_21ed69e962399c06f1b0a7f36f\" ON \"tool_call_records\" (\"workspace_id\", \"agent_execution_id\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_4c0ad721372fc63d224cafcf04\" ON \"tool_call_records\" (\"source_workspace_id\", \"release_set_id\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_970839bacb6c736ad24b42c8df\" ON \"tool_call_records\" (\"source_workspace_id\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_8826beb0b0ce65771b0953e528\" ON \"tool_call_records\" (\"executionId\", \"correlationId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_3b65a0f83f1df30007a0b12732\" ON \"tool_call_records\" (\"executionId\", \"traceId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_2e7399d8728dea7bd6f86dd851\" ON \"tool_call_records\" (\"toolName\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_9059d1e26ba3fb5c8aec429bdd\" ON \"tool_call_records\" (\"executionId\") ","parameters":[]},
  {"query":"CREATE TYPE \"public\".\"agent_executions_resolution_mode_enum\" AS ENUM('active_snapshot', 'candidate_test')","parameters":[]},
  {"query":"CREATE TABLE \"agent_executions\" (\"id\" uuid NOT NULL, \"workspaceId\" uuid NOT NULL, \"source_workspace_id\" uuid, \"resolution_mode\" \"public\".\"agent_executions_resolution_mode_enum\", \"candidate_isolation_binding_id\" uuid, \"candidate_isolation_snapshot_hash\" character varying(71), \"release_set_id\" uuid, \"agent_version_id\" uuid, \"bundle_digest\" character varying(71), \"goal_snapshot_id\" uuid, \"goal_snapshot_hash\" character varying(71), \"initial_context_manifest_id\" uuid, \"initial_context_manifest_hash\" character varying(71), \"principal_snapshot\" jsonb, \"trace_id\" character varying(100), \"correlation_id\" character varying(100), \"parent_flow_execution_id\" uuid, \"parent_flow_step_log_id\" uuid, \"agentId\" uuid NOT NULL, \"triggerType\" character varying(20) NOT NULL, \"triggerSource\" character varying(20) NOT NULL, \"triggeredBy\" uuid, \"triggerPayload\" jsonb, \"rawInput\" text, \"intent\" character varying(100), \"intentConfidence\" numeric(3,2), \"status\" character varying(30) NOT NULL DEFAULT 'pending', \"outputType\" character varying(20), \"outputContent\" jsonb, \"outputSummary\" text, \"totalInputTokens\" integer NOT NULL DEFAULT '0', \"totalOutputTokens\" integer NOT NULL DEFAULT '0', \"totalCost\" numeric(10,4) NOT NULL DEFAULT '0', \"aiProviderSummary\" jsonb, \"outcomeType\" character varying(50), \"outcomeRecordId\" uuid, \"participationScore\" numeric(5,2), \"targetObjectName\" character varying(100), \"targetRecordId\" uuid, \"targetRecordName\" text, \"startedAt\" TIMESTAMP WITH TIME ZONE, \"completedAt\" TIMESTAMP WITH TIME ZONE, \"durationMs\" integer, \"createdAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_1be5b595730621debe308ad2c6d\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE INDEX \"IDX_25ae613b67a06139f0b27ad3fd\" ON \"agent_executions\" (\"source_workspace_id\", \"release_set_id\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_c17130ffaf8a5104d76a27e4bb\" ON \"agent_executions\" (\"resolution_mode\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_e6cf1511524a51e6f95f4a5ebf\" ON \"agent_executions\" (\"source_workspace_id\") ","parameters":[]},
  {"query":"CREATE UNIQUE INDEX \"UQ_agent_executions_workspace_id\" ON \"agent_executions\" (\"workspaceId\", \"id\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_20962c6bb95103a2612a4a1320\" ON \"agent_executions\" (\"workspaceId\", \"targetObjectName\", \"targetRecordId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_eeee7ad207d0c889357338c1ca\" ON \"agent_executions\" (\"workspaceId\", \"createdAt\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_007d4ec13085663ba544fcf7b2\" ON \"agent_executions\" (\"workspaceId\", \"triggerSource\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_ff38dfca2f1c554b1ffddf1a7b\" ON \"agent_executions\" (\"workspaceId\", \"status\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_388ffce0e5638e977f6de7385e\" ON \"agent_executions\" (\"agentId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_9119ad0ddadb4a55bbe58e045f\" ON \"agent_executions\" (\"workspaceId\") ","parameters":[]},
  {"query":"CREATE TYPE \"public\".\"menu_items_type_enum\" AS ENUM('object', 'page', 'url', 'folder')","parameters":[]},
  {"query":"CREATE TABLE \"menu_items\" (\"id\" uuid NOT NULL, \"name\" character varying NOT NULL, \"apiName\" character varying(100) NOT NULL, \"icon\" character varying, \"i18n_key\" character varying, \"translations\" jsonb, \"path\" character varying, \"type\" \"public\".\"menu_items_type_enum\" NOT NULL DEFAULT 'page', \"targetObjectId\" character varying, \"position\" integer NOT NULL DEFAULT '0', \"isActive\" boolean NOT NULL DEFAULT true, \"appId\" uuid NOT NULL, \"parentId\" uuid, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_57e6188f929e5dc6919168620c8\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE UNIQUE INDEX \"IDX_menu_items_app_api_name_unique\" ON \"menu_items\" (\"appId\", \"apiName\") ","parameters":[]},
  {"query":"CREATE TYPE \"public\".\"workspaces_environmenttype_enum\" AS ENUM('local', 'sandbox', 'staging', 'production')","parameters":[]},
  {"query":"CREATE TABLE \"workspaces\" (\"id\" uuid NOT NULL, \"displayName\" character varying NOT NULL, \"logo\" character varying, \"logoDocumentId\" uuid, \"inviteHash\" character varying, \"allowImpersonation\" boolean NOT NULL DEFAULT false, \"environmentType\" \"public\".\"workspaces_environmenttype_enum\" NOT NULL DEFAULT 'production', \"language\" character varying DEFAULT 'zh-CN', \"dateFormat\" character varying DEFAULT 'YYYY-MM-DD', \"timeFormat\" character varying DEFAULT '24h', \"numberFormat\" character varying DEFAULT 'comma-dot', \"currencyPosition\" character varying DEFAULT 'before', \"timezone\" character varying DEFAULT 'Asia/Shanghai', \"businessHoursSchedule\" jsonb, \"isGoogleAuthEnabled\" boolean NOT NULL DEFAULT true, \"isMicrosoftAuthEnabled\" boolean NOT NULL DEFAULT false, \"isPasswordAuthEnabled\" boolean NOT NULL DEFAULT true, \"isPublicInviteLinkEnabled\" boolean NOT NULL DEFAULT true, \"isTwoFactorAuthenticationEnforced\" boolean NOT NULL DEFAULT false, \"trashRetentionDays\" integer NOT NULL DEFAULT '14', \"deletionRequestedAt\" TIMESTAMP WITH TIME ZONE, \"deletionScheduledAt\" TIMESTAMP WITH TIME ZONE, \"editableProfileFields\" jsonb DEFAULT '[\"email\",\"firstName\",\"lastName\",\"profilePicture\"]'::jsonb, \"hasValidEnterpriseKey\" boolean NOT NULL DEFAULT false, \"isGoogleAuthBypassEnabled\" boolean NOT NULL DEFAULT false, \"isMicrosoftAuthBypassEnabled\" boolean NOT NULL DEFAULT false, \"isPasswordAuthBypassEnabled\" boolean NOT NULL DEFAULT false, \"sessionTimeoutMinutes\" integer NOT NULL DEFAULT '480', \"isJitProvisioningEnabled\" boolean NOT NULL DEFAULT false, \"fiscalYearStartMonth\" smallint NOT NULL DEFAULT '1', \"homeDashboardId\" uuid, \"homePageDefinitionId\" uuid, \"fastModel\" character varying(100), \"smartModel\" character varying(100), \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_098656ae401f3e1a4586f47fd8e\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE TABLE \"app_permissions\" (\"id\" uuid NOT NULL, \"roleId\" uuid NOT NULL, \"appId\" uuid NOT NULL, \"visible\" boolean NOT NULL DEFAULT true, \"isDefault\" boolean NOT NULL DEFAULT false, \"createdAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"IDX_APP_PERMISSION_ROLE_ID_APP_ID_UNIQUE\" UNIQUE (\"roleId\", \"appId\"), CONSTRAINT \"PK_2ffc521a3e9b111cab3dbcca274\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE INDEX \"IDX_APP_PERMISSION_APP_ID\" ON \"app_permissions\" (\"appId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_APP_PERMISSION_ROLE_ID\" ON \"app_permissions\" (\"roleId\") ","parameters":[]},
  {"query":"CREATE TYPE \"public\".\"apps_platform_enum\" AS ENUM('pc', 'mobile', 'both')","parameters":[]},
  {"query":"CREATE TYPE \"public\".\"apps_navstyle_enum\" AS ENUM('standard', 'console')","parameters":[]},
  {"query":"CREATE TABLE \"apps\" (\"id\" uuid NOT NULL, \"apiName\" character varying NOT NULL, \"name\" character varying NOT NULL, \"description\" character varying, \"i18n_key\" character varying, \"translations\" jsonb, \"icon\" character varying, \"color\" character varying, \"position\" integer NOT NULL DEFAULT '0', \"isDefault\" boolean NOT NULL DEFAULT false, \"isSystem\" boolean NOT NULL DEFAULT false, \"isActive\" boolean NOT NULL DEFAULT true, \"platform\" \"public\".\"apps_platform_enum\" NOT NULL DEFAULT 'both', \"navStyle\" \"public\".\"apps_navstyle_enum\" NOT NULL DEFAULT 'standard', \"logoUrl\" character varying, \"utilityItems\" text, \"assignedRoles\" text, \"allowPersonalization\" boolean NOT NULL DEFAULT true, \"homeDashboardId\" uuid, \"homePageDefinitionId\" uuid, \"workspaceId\" uuid, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_c5121fda0f8268f1f7f84134e19\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE UNIQUE INDEX \"UQ_apps_workspace_api_name\" ON \"apps\" (\"workspaceId\", \"apiName\") ","parameters":[]},
  {"query":"CREATE TYPE \"public\".\"approval_instances_status_enum\" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'RECALLED', 'EXPIRED')","parameters":[]},
  {"query":"CREATE TYPE \"public\".\"approval_instances_decision_actor_kind_enum\" AS ENUM('human', 'system_expiry')","parameters":[]},
  {"query":"CREATE TABLE \"approval_instances\" (\"id\" uuid NOT NULL, \"workspace_id\" uuid NOT NULL, \"process_id\" uuid NOT NULL, \"record_id\" uuid NOT NULL, \"object_name\" character varying(100) NOT NULL, \"status\" \"public\".\"approval_instances_status_enum\" NOT NULL DEFAULT 'PENDING', \"current_step_index\" integer NOT NULL DEFAULT '0', \"approval_policy_revision_id\" uuid, \"approval_policy_checksum\" character varying(71), \"subject_type\" character varying(32), \"subject_id\" uuid, \"tool_call_id\" uuid, \"governance_context\" jsonb, \"governance_context_digest\" character varying(71), \"subject_idempotency_key_hash\" character varying(71), \"supersedes_approval_id\" uuid, \"superseded_by_approval_id\" uuid, \"superseded_at\" TIMESTAMP WITH TIME ZONE, \"supersession_reason\" character varying(64), \"superseded_by_actor_id\" uuid, \"expires_at\" TIMESTAMP WITH TIME ZONE, \"step_version\" bigint NOT NULL DEFAULT '0', \"decision_version\" bigint NOT NULL DEFAULT '0', \"consumed_at\" TIMESTAMP WITH TIME ZONE, \"consumed_by_kind\" character varying(64), \"consumed_by_id\" uuid, \"decision_actor_kind\" \"public\".\"approval_instances_decision_actor_kind_enum\", \"decision_actor_id\" uuid, \"history\" jsonb NOT NULL DEFAULT '[]', \"submitted_by\" uuid NOT NULL, \"submitted_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"completed_at\" TIMESTAMP WITH TIME ZONE, CONSTRAINT \"PK_176afd7f1ecc4cbde3db8bf533d\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE INDEX \"IDX_63af2517199a04154b130f676b\" ON \"approval_instances\" (\"status\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_b9c06b18324b53de6ce8f1423e\" ON \"approval_instances\" (\"process_id\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_530a66f3d2c4de66d78168ed7d\" ON \"approval_instances\" (\"workspace_id\", \"record_id\") ","parameters":[]},
  {"query":"CREATE TABLE \"org_nodes\" (\"id\" uuid NOT NULL, \"workspaceId\" uuid NOT NULL, \"label\" character varying(255) NOT NULL, \"apiName\" character varying(255) NOT NULL, \"name\" character varying(255) NOT NULL, \"parentId\" uuid, \"position\" integer NOT NULL DEFAULT '0', \"createdAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_89534649e957a341d82ed3572b1\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE INDEX \"IDX_ORG_NODE_WORKSPACE_PARENT_POSITION\" ON \"org_nodes\" (\"workspaceId\", \"parentId\", \"position\") ","parameters":[]},
  {"query":"CREATE UNIQUE INDEX \"IDX_ORG_NODE_API_NAME_WORKSPACE_ID_UNIQUE\" ON \"org_nodes\" (\"apiName\", \"workspaceId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_ORG_NODE_PARENT_ID\" ON \"org_nodes\" (\"parentId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_ORG_NODE_WORKSPACE_ID\" ON \"org_nodes\" (\"workspaceId\") ","parameters":[]},
  {"query":"CREATE TABLE \"users\" (\"id\" uuid NOT NULL, \"username\" character varying NOT NULL, \"email\" character varying NOT NULL, \"passwordHash\" character varying NOT NULL, \"firstName\" character varying NOT NULL DEFAULT '', \"lastName\" character varying NOT NULL DEFAULT '', \"avatarUrl\" character varying, \"locale\" character varying NOT NULL DEFAULT 'en', \"defaultWorkspaceId\" uuid, \"phone\" character varying(50), \"title\" character varying(100), \"department\" character varying(100), \"isActive\" boolean NOT NULL DEFAULT true, \"isServiceAccount\" boolean NOT NULL DEFAULT false, \"timeZone\" character varying(50) NOT NULL DEFAULT 'UTC', \"managerId\" uuid, \"roleId\" uuid, \"orgNodeId\" uuid, \"dateFormat\" character varying(20) NOT NULL DEFAULT 'YYYY-MM-DD', \"timeFormat\" character varying(20) NOT NULL DEFAULT 'HH:mm:ss', \"alias\" character varying(50), \"extension\" character varying(20), \"fax\" character varying(50), \"company\" character varying(100), \"division\" character varying(100), \"address\" jsonb, \"delegatedApproverId\" uuid, \"federationId\" character varying(255), \"numberFormat\" character varying(20) NOT NULL DEFAULT '1,000.00', \"colorScheme\" character varying(20) NOT NULL DEFAULT 'light', \"calendarStartDay\" integer NOT NULL DEFAULT '0', \"compactMode\" boolean NOT NULL DEFAULT false, \"showWelcomeBanner\" boolean NOT NULL DEFAULT true, \"notificationPreferences\" jsonb NOT NULL DEFAULT '{}', \"isEmailVerified\" boolean NOT NULL DEFAULT false, \"lastLoginAt\" TIMESTAMP WITH TIME ZONE, \"isFrozen\" boolean NOT NULL DEFAULT false, \"supportImpersonationEnabled\" boolean NOT NULL DEFAULT false, \"supportImpersonationExpiresAt\" TIMESTAMP WITH TIME ZONE, \"supportImpersonationGrantedById\" uuid, \"supportImpersonationGrantedAt\" TIMESTAMP WITH TIME ZONE, \"frozenAt\" TIMESTAMP WITH TIME ZONE, \"frozenById\" uuid, \"frozenReason\" character varying(500), \"hasPasswordSet\" boolean NOT NULL DEFAULT false, \"activationToken\" character varying(255), \"activationTokenExpiresAt\" TIMESTAMP WITH TIME ZONE, \"passwordResetToken\" character varying(255), \"passwordResetTokenExpiresAt\" TIMESTAMP WITH TIME ZONE, \"failedLoginAttempts\" integer NOT NULL DEFAULT '0', \"lastFailedLoginAt\" TIMESTAMP WITH TIME ZONE, \"activatedAt\" TIMESTAMP WITH TIME ZONE, \"last_step_up_at\" TIMESTAMP WITH TIME ZONE, \"createdAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"UQ_fe0bb3f6520ee0469504521e710\" UNIQUE (\"username\"), CONSTRAINT \"PK_a3ffb1c0c8416b9fc6f907b7433\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE INDEX \"IDX_USER_MANAGER_ID\" ON \"users\" (\"managerId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_USER_ORG_NODE_ID\" ON \"users\" (\"orgNodeId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_USER_ROLE_ID\" ON \"users\" (\"roleId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_USER_DEPARTMENT\" ON \"users\" (\"department\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_USER_IS_ACTIVE\" ON \"users\" (\"isActive\") ","parameters":[]},
  {"query":"CREATE TABLE \"roles\" (\"id\" uuid NOT NULL, \"workspaceId\" uuid NOT NULL, \"label\" character varying(100) NOT NULL, \"apiName\" character varying(100) NOT NULL, \"name\" character varying(100) NOT NULL, \"description\" text, \"isSystem\" boolean NOT NULL DEFAULT false, \"isActive\" boolean NOT NULL DEFAULT true, \"canManageUsers\" boolean NOT NULL DEFAULT false, \"canManageRoles\" boolean NOT NULL DEFAULT false, \"canManageApps\" boolean NOT NULL DEFAULT false, \"canCustomizeObjects\" boolean NOT NULL DEFAULT false, \"canDevelop\" boolean NOT NULL DEFAULT false, \"canManageDataSharing\" boolean NOT NULL DEFAULT false, \"canViewSetup\" boolean NOT NULL DEFAULT false, \"capabilityGrants\" text array NOT NULL DEFAULT '{}', \"maxConcurrentSessions\" integer NOT NULL DEFAULT '5', \"sessionLimitPolicy\" character varying(20) NOT NULL DEFAULT 'KICK_OLDEST', \"createdAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"createdBy\" uuid, \"updatedBy\" uuid, CONSTRAINT \"PK_c1433d71a4838793a49dcad46ab\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE INDEX \"IDX_ROLE_IS_ACTIVE\" ON \"roles\" (\"isActive\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_ROLE_IS_SYSTEM\" ON \"roles\" (\"isSystem\") ","parameters":[]},
  {"query":"CREATE UNIQUE INDEX \"IDX_ROLE_API_NAME_WORKSPACE_ID_UNIQUE\" ON \"roles\" (\"apiName\", \"workspaceId\") ","parameters":[]},
  {"query":"CREATE UNIQUE INDEX \"IDX_ROLE_NAME_WORKSPACE_ID_UNIQUE\" ON \"roles\" (\"name\", \"workspaceId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_ROLE_WORKSPACE_ID\" ON \"roles\" (\"workspaceId\") ","parameters":[]},
  {"query":"CREATE TABLE \"login_ip_ranges\" (\"id\" uuid NOT NULL, \"roleId\" uuid NOT NULL, \"workspaceId\" uuid NOT NULL, \"startIp\" character varying(45), \"endIp\" character varying(45), \"cidr\" character varying(49), \"description\" text, \"isActive\" boolean NOT NULL DEFAULT true, \"createdAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"chk_ip_range_mode\" CHECK (\"cidr\" IS NOT NULL OR (\"startIp\" IS NOT NULL AND \"endIp\" IS NOT NULL)), CONSTRAINT \"PK_2ef61736c85eb7774d3a3a3ee16\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE INDEX \"idx_login_ip_ranges_role_workspace\" ON \"login_ip_ranges\" (\"roleId\", \"workspaceId\") ","parameters":[]},
  {"query":"CREATE TYPE \"public\".\"execution_logs_type_enum\" AS ENUM('function', 'trigger', 'event')","parameters":[]},
  {"query":"CREATE TYPE \"public\".\"execution_logs_status_enum\" AS ENUM('success', 'error', 'timeout')","parameters":[]},
  {"query":"CREATE TABLE \"execution_logs\" (\"id\" uuid NOT NULL, \"workspaceId\" character varying NOT NULL, \"type\" \"public\".\"execution_logs_type_enum\" NOT NULL, \"sourceId\" character varying NOT NULL, \"sourceName\" character varying NOT NULL, \"artifactApiName\" character varying(100), \"status\" \"public\".\"execution_logs_status_enum\" NOT NULL, \"duration\" integer NOT NULL, \"input\" jsonb, \"output\" jsonb, \"logs\" text, \"error\" text, \"packageName\" character varying(255), \"packageVersion\" character varying(64), \"providerId\" character varying(64), \"policyId\" character varying(128), \"traceId\" character varying(128), \"correlationId\" character varying(128), \"sourceHash\" character varying(128), \"compiledHash\" character varying(128), \"governanceRecord\" jsonb, \"diagnosticRecord\" jsonb, \"executedAt\" TIMESTAMP NOT NULL DEFAULT now(), \"executedBy\" character varying NOT NULL, CONSTRAINT \"PK_9db55f176b2d494e695536f03a7\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE INDEX \"IDX_d444e48cde4350af7cdb6304f7\" ON \"execution_logs\" (\"workspaceId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_42c17747348667299f61ee40c7\" ON \"execution_logs\" (\"workspaceId\", \"executedAt\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_95714684b49ae9fd4f31acd213\" ON \"execution_logs\" (\"workspaceId\", \"sourceId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_0577b191fe465bfa8c2aac3018\" ON \"execution_logs\" (\"workspaceId\", \"type\") ","parameters":[]},
  {"query":"CREATE TABLE \"guardrail_logs\" (\"id\" uuid NOT NULL, \"workspace_id\" uuid NOT NULL, \"execution_id\" uuid, \"rule_id\" uuid, \"rule_name\" character varying(200), \"risk_level\" character varying(5) NOT NULL, \"operation_type\" character varying(50), \"object_api_name\" character varying(100), \"field_api_names\" text array, \"action_taken\" character varying(50) NOT NULL, \"auto_approved\" boolean NOT NULL DEFAULT false, \"approval_id\" uuid, \"approver_id\" uuid, \"approved_at\" TIMESTAMP WITH TIME ZONE, \"approval_status\" character varying(20), \"context\" jsonb, \"created_at\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_85f5208aeb1003c9db2e5425d6a\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE INDEX \"idx_guardrail_log_risk\" ON \"guardrail_logs\" (\"workspace_id\", \"risk_level\") ","parameters":[]},
  {"query":"CREATE INDEX \"idx_guardrail_log_execution\" ON \"guardrail_logs\" (\"execution_id\") ","parameters":[]},
  {"query":"CREATE INDEX \"idx_guardrail_log_workspace_time\" ON \"guardrail_logs\" (\"workspace_id\", \"created_at\") ","parameters":[]},
  {"query":"CREATE TABLE \"nav_item_permissions\" (\"id\" uuid NOT NULL, \"roleId\" uuid NOT NULL, \"menuItemId\" uuid NOT NULL, \"visible\" boolean NOT NULL DEFAULT true, \"createdAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"IDX_NAV_ITEM_PERMISSION_ROLE_ID_MENU_ITEM_ID_UNIQUE\" UNIQUE (\"roleId\", \"menuItemId\"), CONSTRAINT \"PK_231afb958189a0053c00d621d9e\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE INDEX \"IDX_NAV_ITEM_PERMISSION_MENU_ITEM_ID\" ON \"nav_item_permissions\" (\"menuItemId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_NAV_ITEM_PERMISSION_ROLE_ID\" ON \"nav_item_permissions\" (\"roleId\") ","parameters":[]},
  {"query":"CREATE TYPE \"public\".\"permission_audit_logs_targettype_enum\" AS ENUM('APP_PERMISSION', 'NAV_ITEM_PERMISSION', 'TAB_PERMISSION', 'RECORD_TYPE_PERMISSION', 'OWD_SETTING', 'SHARING_RULE', 'ORG_NODE', 'USER_ORG_ASSIGNMENT', 'ROLE', 'PERMISSION_SET', 'PERMISSION_SET_ASSIGNMENT', 'PUBLIC_GROUP', 'PUBLIC_GROUP_MEMBER', 'OBJECT_PERMISSION', 'FIELD_PERMISSION', 'USER_ROLE_ASSIGNMENT')","parameters":[]},
  {"query":"CREATE TYPE \"public\".\"permission_audit_logs_action_enum\" AS ENUM('CREATE', 'UPDATE', 'DELETE')","parameters":[]},
  {"query":"CREATE TABLE \"permission_audit_logs\" (\"id\" uuid NOT NULL, \"workspaceId\" uuid NOT NULL, \"userId\" uuid NOT NULL, \"roleId\" uuid, \"targetType\" \"public\".\"permission_audit_logs_targettype_enum\" NOT NULL, \"targetId\" uuid NOT NULL, \"action\" \"public\".\"permission_audit_logs_action_enum\" NOT NULL, \"previousValues\" jsonb, \"newValues\" jsonb, \"metadata\" jsonb, \"ipAddress\" character varying(45), \"userAgent\" text, \"createdAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_49174317d9b9185a3fe02f80506\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE INDEX \"IDX_PERMISSION_AUDIT_LOG_CREATED_AT\" ON \"permission_audit_logs\" (\"createdAt\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_PERMISSION_AUDIT_LOG_TARGET_TYPE\" ON \"permission_audit_logs\" (\"targetType\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_PERMISSION_AUDIT_LOG_ROLE_ID\" ON \"permission_audit_logs\" (\"roleId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_PERMISSION_AUDIT_LOG_USER_ID\" ON \"permission_audit_logs\" (\"userId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_PERMISSION_AUDIT_LOG_WORKSPACE_ID\" ON \"permission_audit_logs\" (\"workspaceId\") ","parameters":[]},
  {"query":"CREATE TABLE \"record_type_permissions\" (\"id\" uuid NOT NULL, \"roleId\" uuid NOT NULL, \"recordTypeId\" uuid NOT NULL, \"objectMetadataId\" uuid NOT NULL, \"canRead\" boolean NOT NULL DEFAULT true, \"canCreate\" boolean NOT NULL DEFAULT true, \"isDefault\" boolean NOT NULL DEFAULT false, \"createdAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"IDX_RECORD_TYPE_PERMISSION_ROLE_ID_RECORD_TYPE_ID_UNIQUE\" UNIQUE (\"roleId\", \"recordTypeId\"), CONSTRAINT \"PK_1376a21eaef74164029a6386141\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE INDEX \"IDX_RECORD_TYPE_PERMISSION_ROLE_OBJECT\" ON \"record_type_permissions\" (\"roleId\", \"objectMetadataId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_RECORD_TYPE_PERMISSION_OBJECT_METADATA_ID\" ON \"record_type_permissions\" (\"objectMetadataId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_RECORD_TYPE_PERMISSION_RECORD_TYPE_ID\" ON \"record_type_permissions\" (\"recordTypeId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_RECORD_TYPE_PERMISSION_ROLE_ID\" ON \"record_type_permissions\" (\"roleId\") ","parameters":[]},
  {"query":"CREATE TABLE \"tab_permissions\" (\"id\" uuid NOT NULL, \"roleId\" uuid NOT NULL, \"menuItemId\" uuid NOT NULL, \"visible\" boolean NOT NULL DEFAULT true, \"isDefault\" boolean NOT NULL DEFAULT false, \"createdAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"IDX_TAB_PERMISSION_ROLE_ID_MENU_ITEM_ID_UNIQUE\" UNIQUE (\"roleId\", \"menuItemId\"), CONSTRAINT \"PK_e1a719449cb113e8992d40c0f93\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE INDEX \"IDX_TAB_PERMISSION_MENU_ITEM_ID\" ON \"tab_permissions\" (\"menuItemId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_TAB_PERMISSION_ROLE_ID\" ON \"tab_permissions\" (\"roleId\") ","parameters":[]},
  {"query":"CREATE TABLE \"workspace_members\" (\"id\" uuid NOT NULL, \"firstName\" character varying NOT NULL DEFAULT '', \"lastName\" character varying NOT NULL DEFAULT '', \"avatarUrl\" character varying, \"locale\" character varying NOT NULL DEFAULT 'en', \"colorScheme\" character varying NOT NULL DEFAULT 'Light', \"workspaceId\" uuid NOT NULL, \"userId\" uuid NOT NULL, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_22ab43ac5865cd62769121d2bc4\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE TABLE \"field_metadata\" (\"id\" uuid NOT NULL, \"type\" character varying NOT NULL, \"name\" character varying NOT NULL, \"label\" character varying NOT NULL, \"description\" character varying, \"helpText\" character varying, \"icon\" character varying, \"isCustom\" boolean NOT NULL DEFAULT false, \"isActive\" boolean NOT NULL DEFAULT true, \"isSystem\" boolean NOT NULL DEFAULT false, \"pii_classification\" character varying(16) NOT NULL DEFAULT 'none', \"isNullable\" boolean NOT NULL DEFAULT true, \"is_search_field\" boolean NOT NULL DEFAULT false, \"search_weight\" character(1) NOT NULL DEFAULT 'D', \"isUnique\" boolean NOT NULL DEFAULT false, \"unique_case_sensitive\" boolean NOT NULL DEFAULT true, \"is_external_id\" boolean NOT NULL DEFAULT false, \"track_history\" boolean NOT NULL DEFAULT false, \"defaultValue\" jsonb, \"options\" jsonb, \"settings\" jsonb, \"isLabelSyncedWithName\" boolean NOT NULL DEFAULT true, \"translations\" jsonb, \"relationDefinition\" jsonb, \"objectMetadataId\" uuid NOT NULL, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"PK_c75db587904cad6af109b5c65f1\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE TABLE \"object_metadata\" (\"id\" uuid NOT NULL, \"workspaceId\" uuid NOT NULL, \"nameSingular\" character varying NOT NULL, \"namePlural\" character varying NOT NULL, \"labelSingular\" character varying NOT NULL, \"labelPlural\" character varying NOT NULL, \"description\" character varying, \"helpText\" character varying, \"icon\" character varying, \"isCustom\" boolean NOT NULL DEFAULT false, \"isRemote\" boolean NOT NULL DEFAULT false, \"isActive\" boolean NOT NULL DEFAULT true, \"isSystem\" boolean NOT NULL DEFAULT false, \"contains_pii\" boolean NOT NULL DEFAULT false, \"isSearchable\" boolean NOT NULL DEFAULT true, \"deployment_status\" character varying(16) NOT NULL DEFAULT 'deployed', \"allow_activities\" boolean NOT NULL DEFAULT true, \"allow_reports\" boolean NOT NULL DEFAULT true, \"allow_search\" boolean NOT NULL DEFAULT true, \"labelIdentifierFieldMetadataId\" character varying, \"imageIdentifierFieldMetadataId\" character varying, \"shortcut\" character varying, \"record_name_format\" character varying, \"record_name_starting_number\" integer, \"layout_config\" jsonb, \"isLabelSyncedWithName\" boolean NOT NULL DEFAULT true, \"keyPrefix\" character varying(5), \"translations\" jsonb, \"settings\" jsonb, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"UQ_433435a9c617a470fbc19d6441c\" UNIQUE (\"keyPrefix\"), CONSTRAINT \"UQ_object_metadata_workspace_name\" UNIQUE (\"workspaceId\", \"nameSingular\"), CONSTRAINT \"PK_c8c5f885767b356949c18c201c1\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE TABLE \"object_permissions\" (\"id\" uuid NOT NULL, \"roleId\" uuid NOT NULL, \"objectMetadataId\" uuid NOT NULL, \"canRead\" boolean NOT NULL DEFAULT false, \"canCreate\" boolean NOT NULL DEFAULT false, \"canEdit\" boolean NOT NULL DEFAULT false, \"canDelete\" boolean NOT NULL DEFAULT false, \"canViewAll\" boolean NOT NULL DEFAULT false, \"canModifyAll\" boolean NOT NULL DEFAULT false, \"createdAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updatedAt\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"IDX_OBJECT_PERMISSION_ROLE_ID_OBJECT_METADATA_ID_UNIQUE\" UNIQUE (\"roleId\", \"objectMetadataId\"), CONSTRAINT \"PK_17e702e8c1ac565dc474d3d718e\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE INDEX \"IDX_OBJECT_PERMISSION_OBJECT_METADATA_ID\" ON \"object_permissions\" (\"objectMetadataId\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_OBJECT_PERMISSION_ROLE_ID\" ON \"object_permissions\" (\"roleId\") ","parameters":[]},
  {"query":"CREATE TABLE \"outbox_events\" (\"id\" uuid NOT NULL, \"workspace_id\" uuid NOT NULL, \"topic\" character varying(64) NOT NULL, \"event_type\" character varying(80) NOT NULL, \"aggregate_type\" character varying(64) NOT NULL, \"aggregate_id\" character varying(64) NOT NULL, \"payload\" jsonb NOT NULL, \"trace_context\" jsonb NOT NULL, \"idempotency_key\" character varying(128), \"created_at\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"published_at\" TIMESTAMP WITH TIME ZONE, \"attempt_count\" integer NOT NULL DEFAULT '0', \"last_error\" text, CONSTRAINT \"PK_6689a16c00d09b8089f6237f1d2\" PRIMARY KEY (\"id\"))","parameters":[]},
  {"query":"CREATE INDEX \"IDX_OUTBOX_WORKSPACE\" ON \"outbox_events\" (\"workspace_id\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_OUTBOX_AGGREGATE\" ON \"outbox_events\" (\"aggregate_type\", \"aggregate_id\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_OUTBOX_TOPIC_PENDING\" ON \"outbox_events\" (\"topic\", \"published_at\") ","parameters":[]},
  {"query":"CREATE INDEX \"IDX_OUTBOX_PENDING\" ON \"outbox_events\" (\"published_at\", \"created_at\") ","parameters":[]},
  {"query":"ALTER TABLE \"react_steps\" ADD CONSTRAINT \"FK_a1f7a68a33cef1e953e01205ada\" FOREIGN KEY (\"executionId\") REFERENCES \"agent_executions\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"tool_call_records\" ADD CONSTRAINT \"FK_9059d1e26ba3fb5c8aec429bdd9\" FOREIGN KEY (\"executionId\") REFERENCES \"agent_executions\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"tool_call_records\" ADD CONSTRAINT \"FK_248e793fab3ea44dc219706da09\" FOREIGN KEY (\"stepId\") REFERENCES \"react_steps\"(\"id\") ON DELETE SET NULL ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"agent_executions\" ADD CONSTRAINT \"FK_388ffce0e5638e977f6de7385ea\" FOREIGN KEY (\"agentId\") REFERENCES \"agents\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"menu_items\" ADD CONSTRAINT \"FK_22cd6145d0aad544f78ad60e857\" FOREIGN KEY (\"appId\") REFERENCES \"apps\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"menu_items\" ADD CONSTRAINT \"FK_b3b0daffdc6cd8e30cca39ccc5e\" FOREIGN KEY (\"parentId\") REFERENCES \"menu_items\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"app_permissions\" ADD CONSTRAINT \"FK_fa636cfbb681d56d7a897c612d0\" FOREIGN KEY (\"appId\") REFERENCES \"apps\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"app_permissions\" ADD CONSTRAINT \"FK_667e95dd60b1ec72b5f764923aa\" FOREIGN KEY (\"roleId\") REFERENCES \"roles\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"apps\" ADD CONSTRAINT \"FK_e58e953ac639081db881cff78f5\" FOREIGN KEY (\"workspaceId\") REFERENCES \"workspaces\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"org_nodes\" ADD CONSTRAINT \"FK_bff5096eb13f271ea37d2ef859c\" FOREIGN KEY (\"parentId\") REFERENCES \"org_nodes\"(\"id\") ON DELETE SET NULL ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"users\" ADD CONSTRAINT \"FK_5d77e050eabd28d203b301235a7\" FOREIGN KEY (\"defaultWorkspaceId\") REFERENCES \"workspaces\"(\"id\") ON DELETE NO ACTION ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"users\" ADD CONSTRAINT \"FK_874662e039ab7d31a71450eb501\" FOREIGN KEY (\"managerId\") REFERENCES \"users\"(\"id\") ON DELETE NO ACTION ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"users\" ADD CONSTRAINT \"FK_368e146b785b574f42ae9e53d5e\" FOREIGN KEY (\"roleId\") REFERENCES \"roles\"(\"id\") ON DELETE NO ACTION ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"users\" ADD CONSTRAINT \"FK_0cfc8bf0b02206d549fe5ee4857\" FOREIGN KEY (\"orgNodeId\") REFERENCES \"org_nodes\"(\"id\") ON DELETE NO ACTION ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"users\" ADD CONSTRAINT \"FK_4f92d9988cb43cdd546bcb4b1a8\" FOREIGN KEY (\"delegatedApproverId\") REFERENCES \"users\"(\"id\") ON DELETE NO ACTION ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"users\" ADD CONSTRAINT \"FK_53ec3810e35fffa65d47e732f87\" FOREIGN KEY (\"supportImpersonationGrantedById\") REFERENCES \"users\"(\"id\") ON DELETE NO ACTION ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"users\" ADD CONSTRAINT \"FK_42bd10ec7ea887bcc982b6aebab\" FOREIGN KEY (\"frozenById\") REFERENCES \"users\"(\"id\") ON DELETE NO ACTION ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"login_ip_ranges\" ADD CONSTRAINT \"FK_e06a9592077aec7af4f63970681\" FOREIGN KEY (\"roleId\") REFERENCES \"roles\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"nav_item_permissions\" ADD CONSTRAINT \"FK_445f3f0ec0c8e59a302e0607157\" FOREIGN KEY (\"menuItemId\") REFERENCES \"menu_items\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"nav_item_permissions\" ADD CONSTRAINT \"FK_92433b4bfa7e8fea033f52dd62f\" FOREIGN KEY (\"roleId\") REFERENCES \"roles\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"record_type_permissions\" ADD CONSTRAINT \"FK_42e93ceb5132209c63e028c834e\" FOREIGN KEY (\"roleId\") REFERENCES \"roles\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"tab_permissions\" ADD CONSTRAINT \"FK_e6d5d42b60076aa8bb0cf9728ae\" FOREIGN KEY (\"menuItemId\") REFERENCES \"menu_items\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"tab_permissions\" ADD CONSTRAINT \"FK_191aeaa408d3f00cfe739e31d9e\" FOREIGN KEY (\"roleId\") REFERENCES \"roles\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"workspace_members\" ADD CONSTRAINT \"FK_0dd45cb52108d0664df4e7e33e6\" FOREIGN KEY (\"workspaceId\") REFERENCES \"workspaces\"(\"id\") ON DELETE NO ACTION ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"workspace_members\" ADD CONSTRAINT \"FK_22176b38813258c2aadaae32448\" FOREIGN KEY (\"userId\") REFERENCES \"users\"(\"id\") ON DELETE NO ACTION ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"field_metadata\" ADD CONSTRAINT \"FK_4f63c32dce193e6a855faad2581\" FOREIGN KEY (\"objectMetadataId\") REFERENCES \"object_metadata\"(\"id\") ON DELETE NO ACTION ON UPDATE NO ACTION","parameters":[]},
  {"query":"ALTER TABLE \"object_permissions\" ADD CONSTRAINT \"FK_28e2ea7cd12f7fe88dca11e1bcb\" FOREIGN KEY (\"roleId\") REFERENCES \"roles\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION","parameters":[]},
]);

const DOWN_QUERIES: readonly BaselineQuery[] = Object.freeze([
  {"query":"ALTER TABLE \"object_permissions\" DROP CONSTRAINT \"FK_28e2ea7cd12f7fe88dca11e1bcb\"","parameters":[]},
  {"query":"ALTER TABLE \"field_metadata\" DROP CONSTRAINT \"FK_4f63c32dce193e6a855faad2581\"","parameters":[]},
  {"query":"ALTER TABLE \"workspace_members\" DROP CONSTRAINT \"FK_22176b38813258c2aadaae32448\"","parameters":[]},
  {"query":"ALTER TABLE \"workspace_members\" DROP CONSTRAINT \"FK_0dd45cb52108d0664df4e7e33e6\"","parameters":[]},
  {"query":"ALTER TABLE \"tab_permissions\" DROP CONSTRAINT \"FK_191aeaa408d3f00cfe739e31d9e\"","parameters":[]},
  {"query":"ALTER TABLE \"tab_permissions\" DROP CONSTRAINT \"FK_e6d5d42b60076aa8bb0cf9728ae\"","parameters":[]},
  {"query":"ALTER TABLE \"record_type_permissions\" DROP CONSTRAINT \"FK_42e93ceb5132209c63e028c834e\"","parameters":[]},
  {"query":"ALTER TABLE \"nav_item_permissions\" DROP CONSTRAINT \"FK_92433b4bfa7e8fea033f52dd62f\"","parameters":[]},
  {"query":"ALTER TABLE \"nav_item_permissions\" DROP CONSTRAINT \"FK_445f3f0ec0c8e59a302e0607157\"","parameters":[]},
  {"query":"ALTER TABLE \"login_ip_ranges\" DROP CONSTRAINT \"FK_e06a9592077aec7af4f63970681\"","parameters":[]},
  {"query":"ALTER TABLE \"users\" DROP CONSTRAINT \"FK_42bd10ec7ea887bcc982b6aebab\"","parameters":[]},
  {"query":"ALTER TABLE \"users\" DROP CONSTRAINT \"FK_53ec3810e35fffa65d47e732f87\"","parameters":[]},
  {"query":"ALTER TABLE \"users\" DROP CONSTRAINT \"FK_4f92d9988cb43cdd546bcb4b1a8\"","parameters":[]},
  {"query":"ALTER TABLE \"users\" DROP CONSTRAINT \"FK_0cfc8bf0b02206d549fe5ee4857\"","parameters":[]},
  {"query":"ALTER TABLE \"users\" DROP CONSTRAINT \"FK_368e146b785b574f42ae9e53d5e\"","parameters":[]},
  {"query":"ALTER TABLE \"users\" DROP CONSTRAINT \"FK_874662e039ab7d31a71450eb501\"","parameters":[]},
  {"query":"ALTER TABLE \"users\" DROP CONSTRAINT \"FK_5d77e050eabd28d203b301235a7\"","parameters":[]},
  {"query":"ALTER TABLE \"org_nodes\" DROP CONSTRAINT \"FK_bff5096eb13f271ea37d2ef859c\"","parameters":[]},
  {"query":"ALTER TABLE \"apps\" DROP CONSTRAINT \"FK_e58e953ac639081db881cff78f5\"","parameters":[]},
  {"query":"ALTER TABLE \"app_permissions\" DROP CONSTRAINT \"FK_667e95dd60b1ec72b5f764923aa\"","parameters":[]},
  {"query":"ALTER TABLE \"app_permissions\" DROP CONSTRAINT \"FK_fa636cfbb681d56d7a897c612d0\"","parameters":[]},
  {"query":"ALTER TABLE \"menu_items\" DROP CONSTRAINT \"FK_b3b0daffdc6cd8e30cca39ccc5e\"","parameters":[]},
  {"query":"ALTER TABLE \"menu_items\" DROP CONSTRAINT \"FK_22cd6145d0aad544f78ad60e857\"","parameters":[]},
  {"query":"ALTER TABLE \"agent_executions\" DROP CONSTRAINT \"FK_388ffce0e5638e977f6de7385ea\"","parameters":[]},
  {"query":"ALTER TABLE \"tool_call_records\" DROP CONSTRAINT \"FK_248e793fab3ea44dc219706da09\"","parameters":[]},
  {"query":"ALTER TABLE \"tool_call_records\" DROP CONSTRAINT \"FK_9059d1e26ba3fb5c8aec429bdd9\"","parameters":[]},
  {"query":"ALTER TABLE \"react_steps\" DROP CONSTRAINT \"FK_a1f7a68a33cef1e953e01205ada\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_OUTBOX_PENDING\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_OUTBOX_TOPIC_PENDING\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_OUTBOX_AGGREGATE\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_OUTBOX_WORKSPACE\"","parameters":[]},
  {"query":"DROP TABLE \"outbox_events\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_OBJECT_PERMISSION_ROLE_ID\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_OBJECT_PERMISSION_OBJECT_METADATA_ID\"","parameters":[]},
  {"query":"DROP TABLE \"object_permissions\"","parameters":[]},
  {"query":"DROP TABLE \"object_metadata\"","parameters":[]},
  {"query":"DROP TABLE \"field_metadata\"","parameters":[]},
  {"query":"DROP TABLE \"workspace_members\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_TAB_PERMISSION_ROLE_ID\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_TAB_PERMISSION_MENU_ITEM_ID\"","parameters":[]},
  {"query":"DROP TABLE \"tab_permissions\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_RECORD_TYPE_PERMISSION_ROLE_ID\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_RECORD_TYPE_PERMISSION_RECORD_TYPE_ID\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_RECORD_TYPE_PERMISSION_OBJECT_METADATA_ID\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_RECORD_TYPE_PERMISSION_ROLE_OBJECT\"","parameters":[]},
  {"query":"DROP TABLE \"record_type_permissions\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_PERMISSION_AUDIT_LOG_WORKSPACE_ID\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_PERMISSION_AUDIT_LOG_USER_ID\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_PERMISSION_AUDIT_LOG_ROLE_ID\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_PERMISSION_AUDIT_LOG_TARGET_TYPE\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_PERMISSION_AUDIT_LOG_CREATED_AT\"","parameters":[]},
  {"query":"DROP TABLE \"permission_audit_logs\"","parameters":[]},
  {"query":"DROP TYPE \"public\".\"permission_audit_logs_action_enum\"","parameters":[]},
  {"query":"DROP TYPE \"public\".\"permission_audit_logs_targettype_enum\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_NAV_ITEM_PERMISSION_ROLE_ID\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_NAV_ITEM_PERMISSION_MENU_ITEM_ID\"","parameters":[]},
  {"query":"DROP TABLE \"nav_item_permissions\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"idx_guardrail_log_workspace_time\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"idx_guardrail_log_execution\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"idx_guardrail_log_risk\"","parameters":[]},
  {"query":"DROP TABLE \"guardrail_logs\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_0577b191fe465bfa8c2aac3018\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_95714684b49ae9fd4f31acd213\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_42c17747348667299f61ee40c7\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_d444e48cde4350af7cdb6304f7\"","parameters":[]},
  {"query":"DROP TABLE \"execution_logs\"","parameters":[]},
  {"query":"DROP TYPE \"public\".\"execution_logs_status_enum\"","parameters":[]},
  {"query":"DROP TYPE \"public\".\"execution_logs_type_enum\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"idx_login_ip_ranges_role_workspace\"","parameters":[]},
  {"query":"DROP TABLE \"login_ip_ranges\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_ROLE_WORKSPACE_ID\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_ROLE_NAME_WORKSPACE_ID_UNIQUE\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_ROLE_API_NAME_WORKSPACE_ID_UNIQUE\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_ROLE_IS_SYSTEM\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_ROLE_IS_ACTIVE\"","parameters":[]},
  {"query":"DROP TABLE \"roles\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_USER_IS_ACTIVE\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_USER_DEPARTMENT\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_USER_ROLE_ID\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_USER_ORG_NODE_ID\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_USER_MANAGER_ID\"","parameters":[]},
  {"query":"DROP TABLE \"users\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_ORG_NODE_WORKSPACE_ID\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_ORG_NODE_PARENT_ID\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_ORG_NODE_API_NAME_WORKSPACE_ID_UNIQUE\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_ORG_NODE_WORKSPACE_PARENT_POSITION\"","parameters":[]},
  {"query":"DROP TABLE \"org_nodes\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_530a66f3d2c4de66d78168ed7d\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_b9c06b18324b53de6ce8f1423e\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_63af2517199a04154b130f676b\"","parameters":[]},
  {"query":"DROP TABLE \"approval_instances\"","parameters":[]},
  {"query":"DROP TYPE \"public\".\"approval_instances_decision_actor_kind_enum\"","parameters":[]},
  {"query":"DROP TYPE \"public\".\"approval_instances_status_enum\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"UQ_apps_workspace_api_name\"","parameters":[]},
  {"query":"DROP TABLE \"apps\"","parameters":[]},
  {"query":"DROP TYPE \"public\".\"apps_navstyle_enum\"","parameters":[]},
  {"query":"DROP TYPE \"public\".\"apps_platform_enum\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_APP_PERMISSION_ROLE_ID\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_APP_PERMISSION_APP_ID\"","parameters":[]},
  {"query":"DROP TABLE \"app_permissions\"","parameters":[]},
  {"query":"DROP TABLE \"workspaces\"","parameters":[]},
  {"query":"DROP TYPE \"public\".\"workspaces_environmenttype_enum\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_menu_items_app_api_name_unique\"","parameters":[]},
  {"query":"DROP TABLE \"menu_items\"","parameters":[]},
  {"query":"DROP TYPE \"public\".\"menu_items_type_enum\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_9119ad0ddadb4a55bbe58e045f\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_388ffce0e5638e977f6de7385e\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_ff38dfca2f1c554b1ffddf1a7b\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_007d4ec13085663ba544fcf7b2\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_eeee7ad207d0c889357338c1ca\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_20962c6bb95103a2612a4a1320\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"UQ_agent_executions_workspace_id\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_e6cf1511524a51e6f95f4a5ebf\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_c17130ffaf8a5104d76a27e4bb\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_25ae613b67a06139f0b27ad3fd\"","parameters":[]},
  {"query":"DROP TABLE \"agent_executions\"","parameters":[]},
  {"query":"DROP TYPE \"public\".\"agent_executions_resolution_mode_enum\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_9059d1e26ba3fb5c8aec429bdd\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_2e7399d8728dea7bd6f86dd851\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_3b65a0f83f1df30007a0b12732\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_8826beb0b0ce65771b0953e528\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_970839bacb6c736ad24b42c8df\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_4c0ad721372fc63d224cafcf04\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_21ed69e962399c06f1b0a7f36f\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_dc3c86e33a0b29c896721a27a7\"","parameters":[]},
  {"query":"DROP TABLE \"tool_call_records\"","parameters":[]},
  {"query":"DROP TYPE \"public\".\"tool_call_records_status_enum\"","parameters":[]},
  {"query":"DROP TYPE \"public\".\"tool_call_records_resolution_mode_enum\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_91ea1fd419e85e7975349da670\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_de8fbe47b4d7da2bf10a0d5a5e\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_e93108251ad8ecd567a435f096\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_abb1456d082dc4c885bec68f21\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_7550a7c4d20f106ffddfc74a92\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"UQ_react_steps_workspace_execution_id\"","parameters":[]},
  {"query":"DROP TABLE \"react_steps\"","parameters":[]},
  {"query":"DROP TYPE \"public\".\"react_steps_resolution_mode_enum\"","parameters":[]},
  {"query":"DROP INDEX \"public\".\"IDX_891465b3cee1cfe275594eb1cd\"","parameters":[]},
  {"query":"DROP TABLE \"agents\"","parameters":[]},
]);

export class CommunityBaseline1785000000000 implements MigrationInterface {
  readonly name = 'CommunityBaseline1785000000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    for (const statement of UP_QUERIES) {
      await queryRunner.query(statement.query, [...statement.parameters]);
    }
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    for (const statement of DOWN_QUERIES) {
      await queryRunner.query(statement.query, [...statement.parameters]);
    }
  }
}
