import {
  Entity,
  PrimaryColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  BeforeInsert,
} from 'typeorm';
import { ObjectType, Field, GraphQLISODateTime, ID } from '@nestjs/graphql';
import { GraphQLJSON } from 'graphql-scalars';
import { generateId } from '../../../common/utils/generate-id';

export enum WorkspaceEnvironmentType {
  LOCAL = 'local',
  SANDBOX = 'sandbox',
  STAGING = 'staging',
  PRODUCTION = 'production',
}

@ObjectType()
@Entity('workspaces')
export class Workspace {
  @Field(() => ID)
  @PrimaryColumn('uuid')
  id: string;

  @BeforeInsert()
  assignId() {
    if (!this.id) this.id = generateId();
  }

  @Field()
  @Column()
  displayName: string;

  @Field(() => String, { nullable: true })
  @Column({ type: 'varchar', nullable: true })
  logo?: string | null;

  /**
   * FK → `content_documents.id`. Populated by the unified file storage
   * pipeline (`unified-file-storage-foundation` spec, Phase 8) once a
   * workspace logo is uploaded through `FileUploadService`.
   *
   * Runtime readers MUST consume this canonical pointer through the
   * file-storage contract. The legacy `logo` URL/sentinel shapes are
   * migration-only artifacts and must not be generated by new upload
   * paths.
   *
   * `ON DELETE SET NULL` at the DB layer (see migration
   * `1771000000006-AddWorkspaceLogoDocumentId`) so a hard-delete of the
   * underlying ContentDocument cannot dangle the workspace.
   */
  @Field(() => String, { nullable: true })
  @Column({ type: 'uuid', nullable: true })
  logoDocumentId?: string | null;

  @Field({ nullable: true })
  @Column({ nullable: true })
  inviteHash?: string;

  @Field({ defaultValue: false })
  @Column({ default: false })
  allowImpersonation: boolean;

  @Field(() => String)
  @Column({
    type: 'enum',
    enum: WorkspaceEnvironmentType,
    default: WorkspaceEnvironmentType.PRODUCTION,
  })
  environmentType: WorkspaceEnvironmentType;

  // Language & locale settings
  @Field({ nullable: true })
  @Column({ nullable: true, default: 'zh-CN' })
  language?: string;

  @Field({ nullable: true })
  @Column({ nullable: true, default: 'YYYY-MM-DD' })
  dateFormat?: string;

  @Field({ nullable: true })
  @Column({ nullable: true, default: '24h' })
  timeFormat?: string;

  @Field({ nullable: true })
  @Column({ nullable: true, default: 'comma-dot' })
  numberFormat?: string;

  @Field({ nullable: true })
  @Column({ nullable: true, default: 'before' })
  currencyPosition?: string;

  // Business hours settings
  @Field({ nullable: true })
  @Column({ nullable: true, default: 'Asia/Shanghai' })
  timezone?: string;

  @Field(() => GraphQLJSON, { nullable: true })
  @Column({ type: 'jsonb', nullable: true })
  businessHoursSchedule?: Record<string, any>[];

  // Security settings
  @Field({ defaultValue: true })
  @Column({ default: true })
  isGoogleAuthEnabled: boolean;

  @Field({ defaultValue: false })
  @Column({ default: false })
  isMicrosoftAuthEnabled: boolean;

  @Field({ defaultValue: true })
  @Column({ default: true })
  isPasswordAuthEnabled: boolean;

  @Field({ defaultValue: true })
  @Column({ default: true })
  isPublicInviteLinkEnabled: boolean;

  @Field({ defaultValue: false })
  @Column({ default: false })
  isTwoFactorAuthenticationEnforced: boolean;

  @Field({ defaultValue: 14 })
  @Column({ default: 14 })
  trashRetentionDays: number;

  @Field(() => GraphQLISODateTime, { nullable: true })
  @Column({ type: 'timestamptz', nullable: true })
  deletionRequestedAt?: Date | null;

  @Field(() => GraphQLISODateTime, { nullable: true })
  @Column({ type: 'timestamptz', nullable: true })
  deletionScheduledAt?: Date | null;

  @Field(() => GraphQLJSON, { nullable: true })
  @Column({
    type: 'jsonb',
    nullable: true,
    default: () => `'["email","firstName","lastName","profilePicture"]'::jsonb`,
  })
  editableProfileFields: string[];

  @Field({ defaultValue: false })
  @Column({ default: false })
  hasValidEnterpriseKey: boolean;

  @Field({ defaultValue: false })
  @Column({ default: false })
  isGoogleAuthBypassEnabled: boolean;

  @Field({ defaultValue: false })
  @Column({ default: false })
  isMicrosoftAuthBypassEnabled: boolean;

  @Field({ defaultValue: false })
  @Column({ default: false })
  isPasswordAuthBypassEnabled: boolean;

  // SSO & Session settings
  @Field({ defaultValue: 480 })
  @Column({ default: 480 })
  sessionTimeoutMinutes: number;

  @Field({ defaultValue: false })
  @Column({ default: false })
  isJitProvisioningEnabled: boolean;

  // Fiscal year configuration: month (1-12) when fiscal year starts
  @Field({ defaultValue: 1 })
  @Column({ type: 'smallint', default: 1 })
  fiscalYearStartMonth: number;

  // Home page dashboard configuration
  @Field({ nullable: true })
  @Column({ type: 'uuid', nullable: true })
  homeDashboardId?: string;

  // Home page Page Builder configuration
  @Field({ nullable: true })
  @Column({ type: 'uuid', nullable: true })
  homePageDefinitionId?: string;

  // AI model preferences (fast/smart tier)
  @Field({ nullable: true })
  @Column({ type: 'varchar', length: 100, nullable: true })
  fastModel?: string;

  @Field({ nullable: true })
  @Column({ type: 'varchar', length: 100, nullable: true })
  smartModel?: string;

  @Field()
  @CreateDateColumn()
  createdAt: Date;

  @Field()
  @UpdateDateColumn()
  updatedAt: Date;
}
